services:
  postgres:
    container_name: pg-book-marketplace
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=book-marketplace'
      - 'POSTGRES_USER=hygorp'
      - 'POSTGRES_PASSWORD=123456'
    ports:
      - '5432:5432'

  rabbitmq:
    container_name: mq-book-marketplace
    image: 'rabbitmq:latest'
    environment:
      - 'RABBITMQ_DEFAULT_PASS=hygorp'
      - 'RABBITMQ_DEFAULT_USER=123456'
    ports:
      - '5672:5672'
