spring:
  application:
    name: "Book Marketplace"

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/book-marketplace
    username: hygorp
    password: 123456

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  rabbitmq:
    host: rabbitmq

server:
  port: 8080
